/*
 * Web Toolbox 日本語文言ファイル
 *
 * 画面に表示される日本語は、原則としてこのファイルだけを書き換えます。
 * 値の右側にある文字列だけを変更してください。
 * キー名（app / common / keyboard など）や記号は変更しないでください。
 * 保存後にブラウザを再読み込みすると反映されます。再ビルドは不要です。
 */
window.WEB_TOOLBOX_TEXTS = {
  app: {
    title: '私のツールの全てです。',
    subtitle: 'huteinotu-runosubetedesu',
    navAria: '私のツールの全てです。',
    loading: '読み込み中の所為です。',
    reset: 'すべてリセットして、',
    startupError: 'エラーコードを吐いてゆくのです。',
    startupFailed: 'エラーコードを吐いてゆくのです。',
    sheetLoadFailed: 'シートを読み込めない所為です。',
    missingLauncher: '{title}の起動関数が見つかりません。',
    credits: {
      button: 'クレジット',
      title: 'クレジット',
      close: '閉じる',
      fontText: '本ソフトでは表示フォントに「源全ゴシック」を使用しています。',
      fontLinkText: '配布元を開く',
      fontUrl: 'https://drive.google.com/drive/folders/19WidrJoCmI5qLJV-eR_ydURIwxB2-DSH',
      licenseText: 'Licensed under SIL Open Font License 1.1',
      licenseUrl: 'http://scripts.sil.org/OFL',
      copyright: '© 2021 全て語り手の所為です。',
      fontInstallTitle: '表示フォントの導入',
      fontInstallHelp: '配布元から取得した「源全ゴシック」のフォントファイルを選択すると、このブラウザに保存してソフト全体へ適用します。',
      fontFileLabel: 'フォントファイル',
      fontInstallButton: 'このフォントを使用',
      fontRemoveButton: '保存したフォントを解除',
      fontChecking: 'フォントを確認中…',
      fontBundledLoaded: 'fonts/GenZenGothic改.ttf を使用中',
      fontStoredLoaded: 'ブラウザに保存した源全ゴシックを使用中',
      fontNotInstalled: '源全ゴシック未導入（代替フォントを使用中）',
      fontSelectFirst: 'フォントファイルを選択してください。',
      fontInstalled: '源全ゴシックを導入し、ソフト全体へ適用しました。',
      fontInstallFailed: 'フォントを導入できませんでした。',
    },
  },

  common: {
    settings: '設定',
    advancedSettings: '詳細設定',
    export: '書き出し',
    preview: 'プレビュー',
    log: 'ログ',
    analyze: '解析',
    play: '再生',
    stop: '停止',
    saveMp4: 'MP4を保存',
    saveWav: 'WAVを保存',
    recording: '書き出し中です。 {percent}%',
    converting: '変換です。 {percent}%',
    convertingMp4: 'MP4に変換している所為です。',
    noMidi: 'MIDIがない為です。',
    noVideo: '動画がないためです。',
    notLoaded: '未読込。',
  },

  tools: {
    tenjify: {
      icon: '⠿',
      title: 'tenjify(3枠)',
      inputPanel: 't3njify',
      inputDescription: '点字暗号を自動で映像化、midi化するソフトです。',
      fields: {
        brailleText: 'Text',
        braillePlaceholder: '例: ⠁⠃⠉',
        brailleHelp: '点字以外の文字は無視されます。',
        bpm: 'BPM',
        leftNote: '左の音',
        centerNote: '中央の音',
        rightNote: '右の音',
        radius: '円の半径',
        gap: '円の間隔',
        stroke: '線の太さ',
        blankRatio: '切替時の無表示（%）',
        blankRatioHelp: '表示の切替境界で、円を何も表示しない時間の割合です。',
        resolution: '解像度',
        fps: 'FPS',
        background: '背景色',
        circle: '円の色',
      },
      buttons: {
        preview: 'プレビュー',
        stop: '停止',
        saveMidi: 'MIDI',
        saveWav: 'WAV',
        saveVideo: '動画',
      },
      exportDescription: 'MIDI・WAV・動画生成',
      previewDescription: '16分音符として表示します。',
      errors: {
        enterBraille: '点字を入力してください。',
      },
      logs: {
        previewStarted: 'プレビュー開始: {count}グループ',
        midiCreated: 'tenji.mid',
        wavCreated: 'tenji.wav',
        recordingStarted: '動画書き出します。',
        videoCreated: '{fileName}を書き出しました。',
      },
    },

    quinzify: {
      icon: '15',
      title: 'quinzify',
      panelTitle: 'qu1n5ify',
      description: '全て十五の所為です。様の『15』模倣を支援するソフトです。',
      fields: {
        displayText: '文字',
        binary: 'バイナリ',
        binaryPlaceholder: '例: 111100001010...',
        binaryHelp: '改行と空白は無視されます。',
        midiFile: 'MIDI',
        fontFile: 'FONT',
        defaultDuration: 'MIDIがないとき',
        fps: 'FPS',
        fontSize: 'フォントサイズ',
        letterSpacing: '字間（px）',
        letterSpacingHelp: '文字間隔をpx単位で調整します。負の値にもできます。',
        resolution: '解像度',
        background: '背景色',
        foreground: '文字色',
      },
      buttons: {
        analyze: '入力を解析します。',
        preview: 'プレビュー',
        stop: '停止',
        saveMp4: 'MP4を保存',
        saveWav: 'WAVを保存',
      },
      wavWarning: '正弦波を合成します。',
      errors: {
        binaryOnly: '0と1だけを入力してください。',
        enterDisplayText: '文字列を入力してください。',
        enterBinary: 'バイナリを入力してください。',
        midiRequiredForWav: 'WAV合成にはMIDIファイルが必要です。',
      },
      logs: {
        analyzed: '解析: {frames}フレーム / {seconds}秒',
        wavCreated: '音声書き出しました。',
        mp4Created: '動画書き出しました。',
      },
    },

    keyboard: {
      icon: '教',
      title: 'kenban-',
      fields: {
        midiFile: 'kenban-',
        minNote: '最低音（白鍵）',
        maxNote: '最高音（白鍵）',
        animationRatio: '押下アニメーション比率',
        animationRatioHelp: '1.0でノート全長、0.5でノート前半だけ押下します。',
        keyboardScale: '鍵盤倍率',
        fps: 'FPS',
        volume: '音量',
        fadeIn: 'フェードイン',
        fadeOut: 'フェードアウト',
      },
      buttons: {
        analyze: '解析',
        play: '再生',
        stop: '停止',
        mp4: 'MP4',
        wav: 'WAV',
      },
      chips: {
        notes: '{count} notes',
        pressed: 'pressed: {count}',
        midiMin: 'MIDI最低音: {name} ({number})',
        midiMax: 'MIDI最高音: {name} ({number})',
        midiMinEmpty: 'MIDI最低音: --',
        midiMaxEmpty: 'MIDI最高音: --',
      },
      errors: {
        rangeMustBeWhite: '白鍵を指定してください。例: C4、B5',
        maxBeforeMin: '最高音は最低音以上にしてください。',
        selectMidi: 'MIDIファイルを選択してください。',
      },
      logs: {
        analyzed: '解析完了: {notes}ノート / {seconds}秒 / 音域 {min}〜{max}',
        wavCreated: '音声書き出しました。',
        mp4Created: '動画書き出しました。',
      },
    },

    morseVideo: {
      icon: '. ..',
      title: '1,2枠モールスアニメーション',
      panelTitle: '1,2枠モールスアニメーション',
      description: 'MIDIファイルを読み込むとノートの長さに合わせてアニメーションを流すツールです。',
      fields: {
        midiFile: 'MIDIファイル',
        inputVideo: '入力動画',
        channel: 'チャンネル指定',
        channelPlaceholder: '空欄=チャンネルを指定しない。',
        outputFps: 'FPS',
        minNote: '最低ノート',
        maxNote: '最高ノート',
        loopSeconds: '動画の数秒だけ用いる。',
        loopPlaceholder: '空欄=動画全長。',
        audio: '音声',
        keepAudio: '入力の音声保持を試みる',
      },
      buttons: {
        analyze: 'ファイル解析',
        previewFirst: '序盤を試す',
        saveMp4: 'MP4を保存',
      },
      speedWarning: '初回書き出し時に31MBの読み込みが発生します。',
      previewTitle: 'プレビュー',
      segmentPanel: 'MIDI区間',
      emptySegments: '区間が表示されます。',
      table: {
        note: 'note',
        start: 'start',
        end: 'end',
        duration: '区間',
        speed: '倍率',
      },
      errors: {
        selectBoth: 'MIDIと入力動画の両方を選択してください。',
        noSegments: '指定条件に一致するノート区間がありません。',
        recordingFailed: '録画失敗。',
      },
      logs: {
        analyzed: '解析: {segments}区間 / 出力 {seconds}秒',
        directMode: '{fps}fps',
        previewCreated: 'プレビュー生成しました。',
        audioUnavailable: 'このブラウザでは動画音声のcaptureStreamが使えません。',
        audioFallback: '無音で再試行します。',
        mp4Created: '動画書き出しました。',
      },
    },

    toMidi: {
      icon: '♪',
      title: 'toMIDI',
      panelTitle: 'toMIDI',
      description: '2〜36進数の文字列を、自動割当または手動割当でMIDI化します。',
      fields: {
        numberString: '文字列',
        numberPlaceholder: '例: 0123456789ABCDEF',
        bpm: 'BPM',
        base: '基数',
        assignmentMode: '割当モード',
        autoMode: '自動割当',
        manualMode: '手動割当',
        noteLength: '音符長',
        whole: '全音符',
        half: '2分音符',
        quarter: '4分音符',
        eighth: '8分音符',
        sixteenth: '16分音符',
        velocity: 'ベロシティ',
        scale: 'スケール',
        baseNote: '基準音',
      },
      buttons: {
        refresh: '割当表を更新',
        saveMidi: 'MIDIを保存',
      },
      mappingPanel: '文字と音階の対応',
      mappingHelp: '「-」を入力すると休符になります。',
      resultPanel: '解析結果',
      table: {
        value: '値',
        note: '音階',
        midi: 'MIDI',
      },
      summary: {
        input: '入力 {count}文字',
        converted: '変換対象 {count}',
        undefined: '未定義 {count}',
      },
      errors: {
        noteOverflow: 'MIDIノート127を超えます。',
        enterString: '数値文字列を入力してください。',
      },
      logs: {
        midiCreated: 'output.midを生成: {events}ノート / {ticks} ticks',
        skipped: '未定義文字をスキップ: {characters}',
      },
    },

    morseToMidi: {
      icon: '.-',
      title: 'morseToMIDI',
      panelTitle: 'モールス信号 → MIDI',
      description: 'モールス信号を指定した長さと間隔でMIDI化します。',
      fields: {
        morseText: 'モールス信号',
        morsePlaceholder: '例: ...---...',
        morseHelp: '下の設定で指定した文字区切り・単語区切りを使用します。',
        dotSymbol: '短点に用いる文字',
        dotSymbolHelp: '初期値: .',
        dashSymbol: '長点に用いる文字',
        dashSymbolHelp: '初期値: -',
        charSeparator: '文字区切りに用いる文字',
        charSeparatorHelp: '初期値は半角スペースです。',
        wordSeparator: '単語区切りに用いる文字',
        wordSeparatorHelp: '初期値: /',
        bpm: 'BPM',
        dot: 'DOT（短点）',
        dash: 'DASH（長点）',
        inGap: 'IN_GAP（符号間）',
        charGap: 'CH_GAP（文字間）',
        wordGap: 'WD_GAP（単語間）',
        note: 'ノート番号／音名',
        noteHelp: '例: 72、C5、F#4、Db5',
        velocity: 'ベロシティ',
      },
      unitHelp: 'DOT・DASH・各GAPの単位は32分音符です。',
      buttons: {
        saveMidi: 'morse.midを保存',
      },
      resultPanel: '解析結果',
      previewPanel: 'MIDIイベント',
      emptyPreview: '有効な短点・長点がありません。',
      previewOmitted: '先頭{count}件のみ表示しています。',
      table: {
        symbol: '符号',
        word: '単語',
        character: '文字',
        startTick: '開始tick',
        durationTick: '長さtick',
      },
      summary: {
        words: '単語 {count}',
        characters: '文字 {count}',
        tones: '発音 {count}',
        duration: '長さ {seconds}秒',
        note: '音高 {name} ({number})',
      },
      errors: {
        noteRequired: 'ノート番号または音名を入力してください。',
        symbolsRequired: '短点・長点・文字区切り・単語区切りは空にできません。',
        symbolConflict: '記号が重複しています: {leftKey}「{left}」 / {rightKey}「{right}」',
      },
      logs: {
        midiCreated: 'morse.midを生成: {events}音 / {ticks} ticks',
        invalidIgnored: '未対応文字を無視しました: {symbols}',
      },
    },

    rPlaybacker: {
      icon: 'R',
      title: 'R_PlayBacker',
      ustPanel: 'R_PlayBacker',
      ustDescription: 'すべあな◘枠のボーカルを編集するソフトです。',
      fields: {
        ustFile: 'UST',
        lyricMode: '歌詞処理',
        rMirror: 'まあ変えなくていいよ：デフォルト',
        fullReverse: 'ノートと歌詞を一緒に逆転',
        notesOnly: 'ノートだけ逆転し歌詞位置を維持',
        audioFile: '音声',
      },
      buttons: {
        saveUst: 'ustを保存',
        previewReverse: '逆再生を聴く',
        saveWav: 'reversed.wavを保存',
      },
      wavPanel: 'WAV反転',
      wavDescription: '逆再生を生成します。',
      infoPanel: 'ファイル情報',
      errors: {
        selectAudio: '音声を選択してください。',
        selectUst: 'USTを選択してください。',
      },
      logs: {
        ustCreated: 'output.ustを生成: {bytes} bytes',
        previewStarted: 'プレビューを開始しました。',
        wavCreated: '音声書き出しました。',
      },
    },

    latticify: {
      icon: '表裏',
      title: 'Latticify',
      panelTitle: 'Latticify',
      description: '全てあなたの所為です。様の『表』『裏』をイメージしたMIDIヴィジュアライザーです。',
      fields: {
        midiFile: 'MIDIファイル',
        mappingFile: 'mapping.txt',
        mappingFileHelp: 'ファイルを選ぶと下のマッピングに読み込みます。',
        mode: '描画モード',
        omote: '表（○）',
        ura: '裏（□）',
        mappingText: 'マッピング',
        mappingPlaceholder: 'C4,D4,E4\nF4,G4,A4',
        mappingHelp: 'カンマ区切りで1行が格子の1行です。空欄・-・_・. は未割当になります。最後の行が短い場合は空欄で補完されます。',
        width: '幅',
        height: '高さ',
        fps: 'FPS',
        stepX: '横間隔',
        stepY: '縦間隔',
        radius: '半径／半辺',
        ringWidth: '輪郭幅',
        ringAlpha: '輪郭最大不透明度',
        fadeIn: '点灯フェードイン秒',
        fadeOut: '点灯フェードアウト秒',
        volume: '音量',
        audioFadeIn: '音声フェードイン秒',
        audioFadeOut: '音声フェードアウト秒',
        mirror: '左右反転',
        mirrorLabel: '左右を反転する',
        background: '背景色',
        inactive: '消灯色',
        active: '点灯色',
        ring: '輪郭色',
      },
      buttons: {
        analyze: '解析',
        play: '再生',
        stop: '停止',
        mp4: 'MP4',
        wav: 'WAV',
      },
      exportWarning: 'MP4には正弦波で合成したMIDI音声を付加します。',
      chips: {
        grid: '{rows}×{cols}',
        mapped: '割当 {count}',
        notes: 'ノート {count}',
        unmapped: '未割当 {count}',
      },
      errors: {
        emptyMapping: 'マッピングを入力してください。',
        noValidMapping: '有効な音階がマッピングにありません。',
        selectMidi: 'MIDIファイルを選択してください。',
      },
      logs: {
        invalidCells: '解釈できないセルを無視しました。: {cells}',
        duplicates: '重複音階は後のセルを採用しました。: {cells}',
        analyzed: '解析: {notes}ノート / {rows}×{cols} / 未割当 {unmapped}',
        mappingLoaded: 'マッピング読み込みました。: {name}',
        wavCreated: '音声書き出しました。',
        mp4Created: '動画書き出しました。',
      },
    },

    onkai: {
      icon: '音',
      title: 'onkai_for_Latticify',
      panelTitle: 'onkai',
      description: 'MIDIファイルに登場する音階を抽出し、mapping.txtとして保存します。',
      fields: {
        midiFile: 'MIDIファイル',
      },
      buttons: {
        analyze: '抽出',
        saveMapping: 'mapping.txtを保存',
        sendToLatticify: 'Latticifyへ渡す',
      },
      resultPanel: '結果',
      resultPlaceholder: '音階が表示される欄です。',
      chips: {
        count: '{count} notes',
        range: '音域: {min}〜{max}',
        rangeEmpty: '音域: --',
      },
      errors: {
        selectMidi: 'MIDIファイルを選択してください。',
        noResult: 'MIDIを解析してください。',
      },
      logs: {
        analyzed: '抽出: {count}音',
        saved: '応え書き出しました。',
        sent: 'マッピングを保存しました。Latticifyを開いてください。',
      },
    },

    template: {
      title: '新しいツール',
      input: '入力',
      run: '実行',
      resultPlaceholder: '結果をここに表示します。',
      noInput: '入力がありません。',
    },
  },


  videoExport: {
    loadingLibrary: '動画変換機能を読み込んでいます。初回は約31MBを取得します。',
    libraryLoadFailed: '動画変換ライブラリを読み込めませんでした。ネット接続またはCDNへのアクセスを確認してください。',
    coreLoadFailed: 'FFmpegの変換エンジンを読み込めませんでした。ネット接続、ブラウザのWorker制限、またはCDNへのアクセスを確認してください。',
    converting: 'MP4に変換しています。',
    conversionFailed: '変換失敗。',
    invalidSegmentDurations: '動画区間の長さが不正です。',
    invalidLoopDuration: '元動画の使用時間が不正です。',
    inputVideoRequired: '入力動画がありません。',
    buildingRetimedVideo: 'MoviePy方式で出力フレームを構築しています。',
    retimingFailed: '動画の速度変換に失敗しました。',
  },

  errors: {
    invalidNoteName: '音名「{name}」を解釈できません。例: C4 / F#3 / Db5',
    invalidNote: '無効な音名です。: {name}',
    midiOutOfRange: 'MIDIノート範囲外です。: {midi}',
    midiVariableLengthEnded: 'MIDIの可変長値が途中で終了しています。',
    invalidRunningStatus: 'MIDI running statusが不正です。',
    notStandardMidi: '標準MIDIファイルではありません。',
    smpteUnsupported: 'SMPTE time divisionのMIDIには未対応です。',
    missingTrackChunk: 'MTrkチャンクが見つかりません: track {track}',
    videoLoadFailed: '動画を読み込めませんでした。',
    videoSeekFailed: '動画のシークに失敗しました。',
    canvasRecordingUnsupported: 'このブラウザはCanvas録画に対応していません。ChromeまたはEdgeを使用してください。',
    recordingFailed: '録画失敗。',
  },
};
